services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - '27017:27017'
    networks:
      - appnet
  backend:
    build: ./Backend
    ports:
      - "8080:8080"
    networks:
      - appnet
    env_file:
      - ./Backend/.env
  frontend:
    build: ./FrontendWeb
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - appnet
    env_file:
      - ./FrontendWeb/.env
networks:
  appnet: