basePath: /
definitions:
  domain.AuthResponse:
    properties:
      token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        type: string
    type: object
  domain.ErrorResponse:
    properties:
      error:
        example: Mensaje de error descriptivo
        type: string
    type: object
  domain.LoginRequest:
    properties:
      email:
        example: usuario@ejemplo.com
        type: string
      password:
        example: password123
        type: string
    required:
    - email
    - password
    type: object
host: localhost:8080
info:
  contact: {}
  description: Documentación de las APIs del proyecto HDC.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: APIs de HDC
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Valida a un usuario con su email y contraseña.
      parameters:
      - description: Credenciales de Inicio de Sesión
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/domain.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Token de autenticación
          schema:
            $ref: '#/definitions/domain.AuthResponse'
        "400":
          description: 'Error: Datos de entrada inválidos'
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "401":
          description: 'Error: Credenciales inválidas'
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Iniciar sesión de usuario
      tags:
      - Autenticación
swagger: "2.0"
